# Generated by Django 4.0.6 on 2022-07-18 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.CharField(max_length=4, verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('category', models.SmallIntegerField(choices=[(1, '阴性人员'), (2, '次密接者'), (3, '密接者'), (4, '阳性人员')], default=1, verbose_name='人员类别')),
                ('crate_time', models.DateField(verbose_name='核酸时间')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.nurse', verbose_name='负责人')),
            ],
        ),
    ]
