# Generated by Django 4.0.6 on 2022-07-20 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_nurse_building_alter_nurse_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('context', models.CharField(max_length=400, verbose_name='内容')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='发布者')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.nurse', verbose_name='发布者')),
            ],
        ),
    ]
