# Generated by Django 4.0.6 on 2022-07-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_notice_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='household',
        ),
    ]
