# Generated by Django 4.0.6 on 2022-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('crate_time', models.DateField(verbose_name='通行时间')),
            ],
        ),
    ]
