# Generated by Django 4.0.6 on 2022-08-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_record_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='current_time',
            field=models.CharField(max_length=64, verbose_name='当前时间'),
        ),
    ]
