# Generated by Django 4.0.6 on 2022-08-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_record_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='crate_time',
        ),
    ]
