# Generated by Django 4.0.6 on 2022-08-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_record_crate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='head',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.resident', verbose_name='住户姓名'),
        ),
    ]
