# Generated by Django 4.0.6 on 2022-08-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_remove_register_name_register_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.resident', verbose_name='住户姓名'),
        ),
    ]
